### ISSUE TITLE
lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/callr/R/callr.rdb' is corrupt

### ISSUE THREAD

**Issue by SebastianHesse** [jlmelville/vizier#1]
Hi,

I just tried installing your package but the get following errors:

> Downloading GitHub repo jlmelville/vizier@master
Error: Failed to install 'vizier' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/callr/R/callr.rdb' is corrupt
In addition: Warning messages:
1: In callr::rcmd_safe(..., env = env, spinner = FALSE, show = FALSE,  :
  restarting interrupted promise evaluation
2: In callr::rcmd_safe(..., env = env, spinner = FALSE, show = FALSE,  :
  internal error -3 in R_decompress1

Could you correct the corrupted data?

Thanks a lot!
Sebastian

**Comment by jlmelville** [comment]
Can you try restarting R? Everything should be ok.

This isn't a problem with the specific package, it's just something that seems to occur when re-installing or upgrading packages which are already loaded in the session (perhaps in your case was `callr` recently upgraded?)

**Comment by SebastianHesse** [comment]
Thanks so much for this reply, sorry to bother you with such triviality!
You were right, a restart solved the issue!
