### ISSUE TITLE
vizier: how to display color legend?

### ISSUE THREAD

**Issue by jielab** [jlmelville/vizier#2]
Dear James:

I used the following code to create a plot:
**umap2 <- umap(report); vizier::embed_plot(umap2$layout, x=gen_info$variant, color_scheme=rainbow)**
![image](https://user-images.githubusercontent.com/26947455/130713944-4fdcd687-c47e-4e97-9d52-c22985a3875c.png)

However, these colors do not tell anything. The color is in gen_info$variant. So, how to display a legend with text for each color?

BTW, this plot does not really look good quality, not fit for publication. Do you have a better recommendation on how to make this?

Thank you & best regards,
Jie

**Comment by jlmelville** [comment]
> However, these colors do not tell anything. The color is in gen_info$variant. So, how to display a legend with text for each color?

You can't. The `embed_plotly` function can show you a legend but it opens a web page. I did some research in how to use the `plot` functions in R to show a legend and it isn't very easy to do it when you have an unknown number of series and don't want to overlap with points on the plot.

> BTW, this plot does not really look good quality, not fit for publication. Do you have a better recommendation on how to make this?

I do not. This package is not intended for publication-quality images. Maybe look at [ggplot2](https://ggplot2.tidyverse.org/)?
